version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  bezkoder-api:
    depends_on:
      - mysqldb
    build: ./bezkoder-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend
    ports:
      - 8080:8080

  bezkoder-ui:
    entrypoint: "sleep infinity"
    depends_on:
      - bezkoder-api
    build:
      context: ./bezkoder-ui
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    volumes:
      - ./bezkoder-ui/src:/bezkoder-ui/src
    ports:
      # - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
      - 8888:3000
    networks:
      - frontend
  # rp:
  #   image: nginx:1.18-alpine
  #   entrypoint: nginx -g "daemon off;"
  #   ports:
  #     - 443:443
  #   restart: unless-stopped
  #   logging:
  #     options:
  #       max-size: 10m
  #   networks:
  #     - backend
  #     - frontend

volumes:
  db:

networks:
  backend:
  frontend: